spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      additional-exclude: database/*
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: 'create-drop'
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        highlight_sql: true
#        jdbc:
#          time_zone: Asia/Ho_Chi_Minh
#        database: mysql
#        dialect: org.hibernate.dialect.MySQLDialect
#        connection.pool_size: 10
#        connection:
#          autocommit: true
  datasource:
#    url: jdbc:mysql://localhost:3306/dacn_repair_service_booking_system
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #datasource 1
    db1:
      url: jdbc:mysql://localhost:3306/dacn_repair_service_booking_system
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
    #datasource 2
#    db2:
#      url: jdbc:sqlite:src/main/resources/database/mydb.sqlite3
#      driver-class-name: org.sqlite.JDBC

init-data:
  admin:
    email: ${ EMAIL_ADMIN }
    password: ${ PASSWORD_ADMIN }
    sdt: ${ SDT_ADMIN }
  token:
    secret-key: ${SECRET_KEY}
    expire-date: 600
    issuer: dacn.com
  token-refresh:
    expire-date: 36

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: dacn-backend
    version: 1.0.0
    url: http://localhost:8080
    title: Dự án cá nhân của Quân

logging:
  level:
    '[com.zaxxer.hikari.HikariConfig]': DEBUG


