spring:
  config:
    activate:
      on-profile: test
  devtools:
    restart:
      additional-exclude: database/*
    add-properties: true
  datasource:
    #datasource 1
    db1:
      url: jdbc:sqlite:src/main/resources/database/dbtestdata.sqlite
      driver-class-name: org.sqlite.JDBC
      dialect: org.hibernate.community.dialect.SQLiteDialect
      jndi-name: db1
    #datasource 2
    db2:
      url: jdbc:sqlite:src/main/resources/database/mydb.sqlite3
      driver-class-name: org.sqlite.JDBC


init-data:
  admin:
    email: ${ EMAIL_ADMIN }
    password: ${ PASSWORD_ADMIN }
    sdt: ${ SDT_ADMIN }
  token:
    secret-key: ${SECRET_KEY}
    expire-date: 360000000
    issuer: dacn.com
  token-refresh:
    expire-date: 360000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: dacn-backend
    version: 1.0.0
    url: http://localhost:8080
    title: Dự án cá nhân của Quân

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG

